groups:
- name: ps
  rules:
  - alert: ps_High_memory_utiluzation
    expr: ((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100) > 85
    for: 1m
    annotations:
      title: 'High memory utiluzation'
      description: 'High memory utiluzation'
    labels:
      severity: 'crit'

#  - alert: CA_Disc_space_problem
#    expr: ((node_filesystem_avail_bytes{job="ubuntu-desktop", mountpoint="/",fstype!="rootfs"} / node_filesystem_size_bytes{job="ubuntu-desktop", mountpoint="/",fstype!="rootfs"}) * 100) < 10
#    for: 1m
#    annotations:
#      title: 'Disk 90% full'
#      description: 'Disk 90% full'
#    labels:
#      severity: 'crit'


#  - alert: CA_node_exporter_down
#    expr: up{job="ubuntu-desktop"} == 0
#    for: 10s
#    annotations:
#      title: 'CA Node Exporter Down'
#      description: 'CA Node Exporter Down'
#    labels:
#      severity: 'crit'

#  - alert: CA_High_CPU_utiluzation
#    expr: node_load1{job="ubuntu-desktop"} > 0.9
#    for: 1m
#    annotations:
#      title: 'High CPU utiluzation'
#      description: 'High CPU utiluzation'
#    labels:
#      severity: 'crit'

#groups:
#— name: ca
#  rules:

#  — alert: ps_High_memory_utiluzation
#    expr: ((node_memory_MemAvailable_bytes{job=»ubuntu-desktop»} / node_memory_MemTotal_bytes{job=»ubuntu-desktop»}) * 100) < 50
#    for: 1m
#    annotations:
#      title: ‘High memory utiluzation’
#      description: ‘High memory utiluzation’
#    labels:
#      severity: ‘crit’

  - alert: ps_Docker_container_stopped
    expr: engine_daemon_container_states_containers{state="stopped"} > 0
    for: 1m
    annotations:
      title: '1 or more docker containers stopped'
      description: '1 or more docker containers stopped'
    labels:
      severity: 'crit'


#  — alert: ps_Docker_container_stopped
#    expr: ((node_memory_MemAvailable_bytes{job=»ubuntu-desktop»} / node_memory_MemTotal_bytes{job=»ubuntu-desktop»}) * 100) < 50
#    for: 30s
#    annotations:
#      title: ‘1 or more containers stopped’
#      description: ‘1 or more containers stopped’
#    labels:
#      severity: ‘crit’

