name: check rules
run-name: ${{ github.actor }} is checking rules
on:
  push:
    branches: [ "main" ]

    
jobs:
  check-rules:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Check Prometheus configs
        uses: peimanja/promtool-github-actions@master
        with:
          promtool_actions_subcommand: 'rules'
          promtool_actions_files: 'prometheus/rules/*.yml'
          promtool_actions_version: '2.14.0'
          promtool_actions_comment: true
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deployment:
    runs-on: ubuntu-latest
    needs: [check-rules]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: "prometheus/rules/rules.yml,1.txt"
     #     source: "prometheus/rules/rules.yml"
          target: "/etc/prometheus2/rules/"
         # strip_components: 2

