name: check rules
run-name: ${{ github.actor }} is checking rules
on:
  push:
    branches: [ "main" ]
    
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Check Prometheus configs
        uses: peimanja/promtool-github-actions@master
        with:
          promtool_actions_subcommand: 'config'
          promtool_actions_files: 'prometheus/config/*.yml'
          promtool_actions_version: '2.14.0'
          promtool_actions_comment: true
