name: check rules
on:
  push:
    branches: [ "main" ]
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Promtool Check'
        uses: karancode/promtool-action@v0.0.1
        with:
          prom_version: '2.9.2'      
          prom_check_subcommand: 'rules'
          prom_check_files: './prometheus/*.yml'
          prom_comment: true
